// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpr6VT2yxaIBU87zVAUoMS-XZflNoOoU',
    appId: '1:598029138727:web:2287635258ba2a637ac702',
    messagingSenderId: '598029138727',
    projectId: 'qvantum-chat',
    authDomain: 'qvantum-chat.firebaseapp.com',
    databaseURL: 'https://qvantum-chat-default-rtdb.firebaseio.com',
    storageBucket: 'qvantum-chat.firebasestorage.app',
    measurementId: 'G-0WZ9SQZJ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDkS8p-cyg6Nzl5JkPjsjAK0nmS_POlE',
    appId: '1:598029138727:android:4c70e65cb5f8bc317ac702',
    messagingSenderId: '598029138727',
    projectId: 'qvantum-chat',
    databaseURL: 'https://qvantum-chat-default-rtdb.firebaseio.com',
    storageBucket: 'qvantum-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQC46GDYMoHJ5UOGrJJQsoESspRCQAo4',
    appId: '1:598029138727:ios:8eb05a8a7f23c9347ac702',
    messagingSenderId: '598029138727',
    projectId: 'qvantum-chat',
    databaseURL: 'https://qvantum-chat-default-rtdb.firebaseio.com',
    storageBucket: 'qvantum-chat.firebasestorage.app',
    iosBundleId: 'com.example.qvantumChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQC46GDYMoHJ5UOGrJJQsoESspRCQAo4',
    appId: '1:598029138727:ios:8eb05a8a7f23c9347ac702',
    messagingSenderId: '598029138727',
    projectId: 'qvantum-chat',
    databaseURL: 'https://qvantum-chat-default-rtdb.firebaseio.com',
    storageBucket: 'qvantum-chat.firebasestorage.app',
    iosBundleId: 'com.example.qvantumChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKpr6VT2yxaIBU87zVAUoMS-XZflNoOoU',
    appId: '1:598029138727:web:098893bfd9f54fb77ac702',
    messagingSenderId: '598029138727',
    projectId: 'qvantum-chat',
    authDomain: 'qvantum-chat.firebaseapp.com',
    databaseURL: 'https://qvantum-chat-default-rtdb.firebaseio.com',
    storageBucket: 'qvantum-chat.firebasestorage.app',
    measurementId: 'G-99KYD9CBFX',
  );
}
